package com.agricycle.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatbotSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatbotSessionAllPropertiesEquals(ChatbotSession expected, ChatbotSession actual) {
        assertChatbotSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertChatbotSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatbotSessionAllUpdatablePropertiesEquals(ChatbotSession expected, ChatbotSession actual) {
        assertChatbotSessionUpdatableFieldsEquals(expected, actual);
        assertChatbotSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatbotSessionAutoGeneratedPropertiesEquals(ChatbotSession expected, ChatbotSession actual) {
        assertThat(actual)
            .as("Verify ChatbotSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatbotSessionUpdatableFieldsEquals(ChatbotSession expected, ChatbotSession actual) {
        assertThat(actual)
            .as("Verify ChatbotSession relevant properties")
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatbotSessionUpdatableRelationshipsEquals(ChatbotSession expected, ChatbotSession actual) {
        assertThat(actual)
            .as("Verify ChatbotSession relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()));
    }
}
