package com.agricycle.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContenuEducatifAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuEducatifAllPropertiesEquals(ContenuEducatif expected, ContenuEducatif actual) {
        assertContenuEducatifAutoGeneratedPropertiesEquals(expected, actual);
        assertContenuEducatifAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuEducatifAllUpdatablePropertiesEquals(ContenuEducatif expected, ContenuEducatif actual) {
        assertContenuEducatifUpdatableFieldsEquals(expected, actual);
        assertContenuEducatifUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuEducatifAutoGeneratedPropertiesEquals(ContenuEducatif expected, ContenuEducatif actual) {
        assertThat(actual)
            .as("Verify ContenuEducatif auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuEducatifUpdatableFieldsEquals(ContenuEducatif expected, ContenuEducatif actual) {
        assertThat(actual)
            .as("Verify ContenuEducatif relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTypeMedia()).as("check typeMedia").isEqualTo(expected.getTypeMedia()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getDatePublication()).as("check datePublication").isEqualTo(expected.getDatePublication()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuEducatifUpdatableRelationshipsEquals(ContenuEducatif expected, ContenuEducatif actual) {
        assertThat(actual)
            .as("Verify ContenuEducatif relationships")
            .satisfies(a -> assertThat(a.getAuteur()).as("check auteur").isEqualTo(expected.getAuteur()));
    }
}
