package com.agricycle.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAllPropertiesEquals(Media expected, Media actual) {
        assertMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAllUpdatablePropertiesEquals(Media expected, Media actual) {
        assertMediaUpdatableFieldsEquals(expected, actual);
        assertMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAutoGeneratedPropertiesEquals(Media expected, Media actual) {
        assertThat(actual)
            .as("Verify Media auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaUpdatableFieldsEquals(Media expected, Media actual) {
        assertThat(actual)
            .as("Verify Media relevant properties")
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getTypeMedia()).as("check typeMedia").isEqualTo(expected.getTypeMedia()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaUpdatableRelationshipsEquals(Media expected, Media actual) {
        assertThat(actual)
            .as("Verify Media relationships")
            .satisfies(a -> assertThat(a.getPost()).as("check post").isEqualTo(expected.getPost()));
    }
}
