package com.agricycle.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QRCodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQRCodeAllPropertiesEquals(QRCode expected, QRCode actual) {
        assertQRCodeAutoGeneratedPropertiesEquals(expected, actual);
        assertQRCodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQRCodeAllUpdatablePropertiesEquals(QRCode expected, QRCode actual) {
        assertQRCodeUpdatableFieldsEquals(expected, actual);
        assertQRCodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQRCodeAutoGeneratedPropertiesEquals(QRCode expected, QRCode actual) {
        assertThat(actual)
            .as("Verify QRCode auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQRCodeUpdatableFieldsEquals(QRCode expected, QRCode actual) {
        assertThat(actual)
            .as("Verify QRCode relevant properties")
            .satisfies(a -> assertThat(a.getValeur()).as("check valeur").isEqualTo(expected.getValeur()))
            .satisfies(a -> assertThat(a.getDateExpiration()).as("check dateExpiration").isEqualTo(expected.getDateExpiration()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQRCodeUpdatableRelationshipsEquals(QRCode expected, QRCode actual) {
        assertThat(actual)
            .as("Verify QRCode relationships")
            .satisfies(a -> assertThat(a.getTransaction()).as("check transaction").isEqualTo(expected.getTransaction()));
    }
}
