export enum UserRole {
  AGRICULTEUR = 'AGRICULTEUR',

  COMMERCANT = 'COMMERCANT',

  TRANSPORTEUR = 'TRANSPORTEUR',

  CONSOMMATEUR = 'CONSOMMATEUR',

  ORGANISATION = 'ORGANISATION',

  ENTREPRISE = 'ENTREPRISE',

  ADMIN = 'ADMIN',
}
